name: Code Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest
    env:
      SERVERPOD_RUN_MODE: "test"
      SERVERPOD_PASSWORD_database: ${{ secrets.SERVERPOD_PASSWORD_DATABASE }}
      SERVERPOD_PASSWORD_redis: ${{ secrets.SERVERPOD_PASSWORD_REDIS }}
      SERVERPOD_PASSWORD_emailSecretHashPepper: ${{ secrets.SERVERPOD_PASSWORD_EMAIL_SECRET_HASH_PEPPER }}
      SERVERPOD_PASSWORD_jwtRefreshTokenHashPepper: ${{ secrets.SERVERPOD_PASSWORD_JWT_REFRESH_TOKEN_HASH_PEPPER }}
      SERVERPOD_PASSWORD_jwtHmacSha512PrivateKey: ${{ secrets.SERVERPOD_PASSWORD_JWT_HMAC_SHA512_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.10.0"
      - name: Start containers
        run: docker compose up --build -d
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test
      - name: Stop containers
        if: always()
        run: docker compose down -v
